/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    teams: Team;
    seasons: Season;
    competitions: Competition;
    matches: Match;
    players: Player;
    registrations: Registration;
    appearances: Appearance;
    users: User;
    media: Media;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    teams: TeamsSelect<false> | TeamsSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    appearances: AppearancesSelect<false> | AppearancesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The sides the club fields. Each one's matches, squad and averages hang off its entry here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * The club's own word for the side — league, challenge league, sunday social, student. Not Squad, side or XI.
   */
  name: string;
  /**
   * What this side is for, as against what it is called. The eligibility rule is about the league and challenge league sides specifically and has to know which is which — and reading that off the name or the slug would rest a league rule on a public address. Renaming /teams/challenge-league for a tidier URL would switch the cap off with nothing to fail and nobody to tell.
   */
  role: 'league' | 'challenge-league' | 'social' | 'student';
  /**
   * The side's address on the site, as in /teams/challenge-league. Changing it breaks every link anybody has saved, so set it once.
   */
  slug: string;
  /**
   * Exactly how this side is named on CricClubs — HKU CC, HKU Belchers CC, HKU Students (UCL). Nothing in a scorecard export says which of our sides it belongs to, so the importer knows only what is recorded here. Leave it empty for a side scored nowhere: the sunday social side's matches are not scored at all, and saying so is the record being honest rather than a field somebody forgot.
   */
  cricclubsNames?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The club's playing years. Create the new one in September, before the first fixture is entered.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * Written as the club writes it — 2025/26. Not 2025-26, which is CricClubs' form, and not 2025/2026.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The leagues and cups the club's sides are entered into. A friendly is not one of these — leave a friendly's Competition empty.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: number;
  /**
   * The competition as Cricket Hong Kong names it, without the division — Saturday Championship, Challenge League, University Cricket League.
   */
  name: string;
  /**
   * The division, if the competition has one — Div 2. The University Cricket League is entered undivided, so leave it empty there.
   */
  division?: string | null;
  /**
   * How the competition is printed. Made from the two fields above.
   */
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every fixture the club plays, before and after it is played. Enter it when the fixture is known; add the result afterwards, on the same record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  /**
   * Which of the club's sides played it. Not the competition — the challenge league side and the Challenge League Div 3 are different things.
   */
  team: number | Team;
  season: number | Season;
  /**
   * Leave empty for a friendly. A friendly genuinely has no competition, and the emptiness is the record saying so.
   */
  competition?: (number | null) | Competition;
  date: string;
  /**
   * 24-hour, as in 14:00. Only needed until the match is played, after which the result is what the page prints.
   */
  startTime?: string | null;
  /**
   * The other club, as the club itself spells it.
   */
  opponent: string;
  /**
   * Home is Sandy Bay. The record prints H or A beside every result.
   */
  venue: 'home' | 'away';
  /**
   * Where it was played — Sandy Bay, Mission Road, Yeung King Playground.
   */
  ground?: string | null;
  /**
   * How long a game it was — 40 overs, T20. Two sides can meet twice in a season over different distances, and the record should say which was which.
   */
  format?: string | null;
  /**
   * The CricClubs page for this match. The site links to it rather than reproducing the ball-by-ball detail.
   */
  scorecard?: string | null;
  /**
   * Fill this in once the match has been played. Until then, leaving the outcome empty is what marks it as a fixture.
   */
  result?: {
    /**
     * Recorded, never worked out from the scores: a rain-adjusted target, a concession and a tie all look like something else from the totals alone.
     */
    outcome?: ('won' | 'lost' | 'drawn' | 'tied' | 'abandoned' | 'conceded') | null;
    /**
     * As a scorer states it — 33 runs, or 5 wickets. Leave it empty if nobody recorded it; a win with no margin is still a win.
     */
    margin?: {
      value?: number | null;
      unit?: ('runs' | 'wickets') | null;
    };
    /**
     * One row per team innings, in the order they were batted. Stored rather than added up from the batters: extras belong to no batter, and one real export's batting figures are a run short of a total that is correct.
     */
    innings?:
      | {
          side: 'hku' | 'opponent';
          runs: number;
          /**
           * Leave empty if the side was bowled out — 151 all out is written 151, never 151/10.
           */
          wickets?: number | null;
          /**
           * Balls, not decimals: 28.3 is 28 overs and 3 balls.
           */
          overs?: string | null;
          /**
           * Byes, leg byes, wides, no balls and penalties — the runs that belong to no batter.
           */
          extras?: number | null;
          /**
           * Part of the extras above, repeated on its own. A bowler is not charged with a bye, so the bowlers' figures only add up to the total once byes and leg byes are taken off — the one check that cannot be made from the extras total alone.
           */
          byes?: number | null;
          legByes?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * How this match is listed. Made from the date and opponent.
   */
  summary?: string | null;
  /**
   * Whether this match still owes a result. A fixture owes nothing yet; once its date has passed and the outcome is still empty, the club has a score to enter.
   */
  standing?: string | null;
  /**
   * Why the importer held this instead of publishing it. Settle each one and re-import, or publish anyway once the paper scorecard has been checked by eye.
   */
  heldReasons?: string[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Everyone who has played for the club. Their figures are worked out from the matches they appear in, so there is nothing to keep up to date here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  /**
   * The club's own spelling of the name — the one that should appear in an averages table. Scorers' spellings go in Aliases below, not here.
   */
  name: string;
  /**
   * How scorers have spelled this person's name — G. Ranasinghe, Garuka R, Ranasinghe G are three aliases of one player. Scorers type names freely, and recording them here is what stops one person becoming three entries in the averages. Most of these are written by the import screen as questions get answered, and this is where a wrong answer is corrected: remove the spelling here and the next import will ask about it again.
   */
  aliases?: string[] | null;
  /**
   * How this player is normally selected to contribute. Not a Team's role (that says what a side is for) — this says what the person does on it. Left empty for most of the record, which predates anyone writing it down. The sidebar says what their appearances suggest; it never fills this in.
   */
  playingRole?: ('batter' | 'bowler' | 'wicketkeeper' | 'all-rounder') | null;
  /**
   * Read from this player's appearances, and never written to the role beside it: a quiet season with the ball does not stop somebody being a bowler, so the decision stays a person's. Blank until they have three appearances, and blank for a player whose scorecards show neither batting nor bowling.
   */
  suggestedRole?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who is registered to which side, for which season. Register a player once per season; the league and challenge league sides are mutually exclusive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  player: number | Player;
  /**
   * A player registered to the league side cannot also be registered to the challenge league side in the same season. The other way round is the same rule — it is symmetric, unlike the two-per-season call-up cap.
   */
  team: number | Team;
  season: number | Season;
  /**
   * Appearances this player has made for the league team this season. A challenge league player may make two; after that they are not eligible for the league team again this season. Blank for every other side, because the rule runs one way only. It counts what scorers wrote down, so treat it as a floor rather than a certainty.
   */
  callUps?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who played, and what they did. One record per player per match — a player who neither batted nor bowled still gets one, because they still played.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearances".
 */
export interface Appearance {
  id: number;
  match: number | Match;
  player: number | Player;
  /**
   * Leave this unticked for did not bat — the player was in the XI but the innings ended before they were needed. That is a different thing from not playing, which is having no appearance here at all.
   */
  batted?: boolean | null;
  batting?: {
    runs?: number | null;
    balls?: number | null;
    fours?: number | null;
    sixes?: number | null;
    /**
     * Recorded rather than worked out from the score, because it is what excludes this innings from the divisor when a batting average is taken.
     */
    notOut?: boolean | null;
    /**
     * The scorer's code — b, lbw, ct, ctw (caught behind), st, ro (run out). Free text on purpose: the list is open, and an unrecognised code is a question for a human rather than a value to guess at.
     */
    howOut?: string | null;
    fielder?: string | null;
    /**
     * On a run out this is merely who was bowling at the time. They did not take the wicket and may not appear in the bowling figures at all.
     */
    bowler?: string | null;
  };
  /**
   * Tick if this player bowled at all.
   */
  bowled?: boolean | null;
  bowling?: {
    /**
     * As a scorer writes it — 7.0, or 3.2 for three overs and two balls.
     */
    overs?: string | null;
    maidens?: number | null;
    runs?: number | null;
    /**
     * Only wickets credited to this bowler. A run out belongs to nobody, which is why the bowlers' wickets routinely add up to less than the wickets that fell.
     */
    wickets?: number | null;
    wides?: number | null;
    noBalls?: number | null;
  };
  /**
   * Always recorded, because fielding is the one thing every player in the XI does.
   */
  fielding?: {
    catches?: number | null;
    runOuts?: number | null;
    stumpings?: number | null;
    /**
     * Part of the catches above, counted again on its own — the ones taken standing up, which a scorer writes ctw rather than ct. Recorded because it is the only thing an export says about who kept wicket, and a keeper's catches are otherwise indistinguishable from an outfielder's. Empty on matches imported before this was kept, which means nobody wrote it down rather than that nobody kept.
     */
    caughtBehind?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Committee members with access to this admin panel. The committee turns over every year — remove the outgoing members when you add the incoming ones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The name shown next to anything this account edits. A person, not a role — “Club Secretary” outlives the person holding it and makes the history unreadable.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photographs and documents used on the public site. Everything uploaded here is public the moment it is saved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the picture shows, for a reader who cannot see it. Describe the moment — “Sandy Bay, second innings, 2025/26” — not the file.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Messages from people who want to play, sent through the site's own form. An Enquiry is not a Player — most never become one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  message: string;
  /**
   * New until somebody on the committee has followed it up. There is no other notification, so this is the whole queue.
   */
  status: 'new' | 'actioned';
  website?: string | null;
  renderedAt?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'competitions';
        value: number | Competition;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'appearances';
        value: number | Appearance;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  slug?: T;
  cricclubsNames?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  name?: T;
  division?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  team?: T;
  season?: T;
  competition?: T;
  date?: T;
  startTime?: T;
  opponent?: T;
  venue?: T;
  ground?: T;
  format?: T;
  scorecard?: T;
  result?:
    | T
    | {
        outcome?: T;
        margin?:
          | T
          | {
              value?: T;
              unit?: T;
            };
        innings?:
          | T
          | {
              side?: T;
              runs?: T;
              wickets?: T;
              overs?: T;
              extras?: T;
              byes?: T;
              legByes?: T;
              id?: T;
            };
      };
  summary?: T;
  standing?: T;
  heldReasons?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  aliases?: T;
  playingRole?: T;
  suggestedRole?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  player?: T;
  team?: T;
  season?: T;
  callUps?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearances_select".
 */
export interface AppearancesSelect<T extends boolean = true> {
  match?: T;
  player?: T;
  batted?: T;
  batting?:
    | T
    | {
        runs?: T;
        balls?: T;
        fours?: T;
        sixes?: T;
        notOut?: T;
        howOut?: T;
        fielder?: T;
        bowler?: T;
      };
  bowled?: T;
  bowling?:
    | T
    | {
        overs?: T;
        maidens?: T;
        runs?: T;
        wickets?: T;
        wides?: T;
        noBalls?: T;
      };
  fielding?:
    | T
    | {
        catches?: T;
        runOuts?: T;
        stumpings?: T;
        caughtBehind?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  status?: T;
  website?: T;
  renderedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
