import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `payload generate:importmap`, and rewritten every time the
    // admin panel gains a custom component. Not ours to lint.
    "src/app/(payload)/admin/importMap.js",
    // Generated by `payload migrate:create`, and a record of what has already
    // run against production — so they are read and never rewritten. Payload's
    // template gives every migration the full argument list whether it uses it
    // or not, which is four unused-variable warnings per file for nothing.
    "src/migrations/**",
  ]),
]);

export default eslintConfig;
